### ISSUE TITLE
Escape hex and octal codes

### ISSUE THREAD

**Issue by applejag** [risor-io/risor#119]
The tokenizer is only considering `\n, \r, \t, \\`

https://github.com/risor-io/risor/blob/e940fd00a2c110ff44d9e0713d025edc7f358959/lexer/lexer.go#L495-L510

Want to be able to do the following:

- Same sequences as Go: https://go.dev/ref/spec#String_literals
  - `\u65e5`
  - `\U00008a9e`
  - `\xff`
- Also the `\033` octal one, commonly used in ANSI color codes (e.g `printf '\033[31mred text\033[0m\n'`)
- Additional hardcoded sequences:
  - `\e` alias for `\033`/`\x1B`, sometimes used in ANSI color codes (e.g in Bash `echo -e '\e[31mred text\e[0m'`)

I'm mostly listing different escape sequences just to make it more consistent, but the ANSI color codes is the most important one to me so that I can do the following in Risor:

```risor
# my-risor-file.risor
c_reset := "\033[0m"
c_red := "\033[31m"

func log_error(err) {
  print('{c_red}error:{c_reset} {err}')
}
```

**Comment by myzie** [comment]
Thanks @applejag, I agree with all this. By any chance would you want to take a stab at the implementation?

I'm sure I can get to it, but it might not be as soon as either of us would like. So I'd be grateful to enlist your help with this :-)

**Comment by applejag** [comment]
Yea sure, I'll give it a go
