### ISSUE TITLE
Kubernetes package 

### ISSUE THREAD

**Issue by luisdavim** [risor-io/risor#123]
I think it would be interesting to have a k8s package to fetch objects from the API.

**Comment by myzie** [comment]
Hi @luisdavim, this would involve wrapping this repo, is that right? https://github.com/kubernetes/client-go

**Comment by luisdavim** [comment]
Yes, but I'd recommend using https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client instead. 

If I have some time today or the next weekend, I can give it a try and open a PR.

**Comment by luisdavim** [comment]
@myzie I've opened https://github.com/risor-io/risor/pull/129 it might still need some work but should be functional and I'd like your input on it.
