### ISSUE TITLE
JmesPath support

### ISSUE THREAD

**Issue by luisdavim** [risor-io/risor#142]
I think https://github.com/jmespath-community/go-jmespath would be a useful addtion to risor, I end up using `jq` or `yq` in most of my bash scripts and this could be a nice alternative for it in risor.

If you agree I can open a PR for it.

**Comment by myzie** [comment]
That'd be great. Just one function to expose, right? `jmespath.search`?

**Comment by luisdavim** [comment]
> That'd be great. Just one function to expose, right? `jmespath.search`?

Yeah and I think we could call it just `jamespath`.

**Comment by luisdavim** [comment]
I've opened #144 for this.
