### ISSUE TITLE
Create a vault module

### ISSUE THREAD

**Issue by luisdavim** [risor-io/risor#147]
Hashicorp vault is quite popular, a vault module could be useful.

**Comment by myzie** [comment]
Sounds good 👍. Let's just keep it on a build flag w/ a separate go.mod like you did with the `kubernetes` module.

**Comment by luisdavim** [comment]
> Sounds good 👍. Let's just keep it on a build flag w/ a separate go.mod like you did with the `kubernetes` module.

Sure, BTW should I have done the same with the jmspath module?

**Comment by myzie** [comment]
I debated bringing that up while reviewing the jmespath PR. For self-contained, small dependencies like that one I think it's less consequential overall, however I do have this rather strong statement in the readme right now:

> Risor is designed to have zero external dependencies in its core libraries.

To keep by that policy it should have its own go.mod.

**Comment by myzie** [comment]
I think putting modules behind a build tag is only necessary for deps that really bloat the size of the CLI binaries. Which is the case for the Go AWS SDK when lots of services are pulled in.

**Comment by luisdavim** [comment]
I've opened https://github.com/risor-io/risor/pull/150 to fix the `jmespath` module and give it its own `go.mod`
