### ISSUE TITLE
allow map[...] syntax on Result objects

### ISSUE THREAD

**Issue by skurfuerst** [risor-io/risor#19]
Hey,

I just discovered Tamarin - great project which I like a lot :)

I naively wanted to do the following:

```
x := json.unmarshal(msg.Data)
x["a"] = 42
return x
```

This did not work, because the result of `json.unmarshal` is a Result object. At other places, Result is magically unwrapped.

What worked is the following (as a workaround):

```
x := json.unmarshal(msg.Data).unwrap()
x["a"] = 42
return x
```

Can this unwrapping be somehow done transparently on map access?

All the best, and keep up the great work,
Sebastian

**Comment by myzie** [comment]
Hi @skurfuerst, thanks for checking in about this.

That use case makes a lot of sense. I think it'd be relatively straight-forward to implement - we'd need to implement the [Container interface methods](https://github.com/cloudcmds/tamarin/blob/main/object/object.go#L102-L124) on the Result type. In the implementation of those calls we'd proxy through to calls on the wrapped object.

More generally, I have mixed feelings on whether it's a good idea to pass through most or all behaviors to the wrapped object 😄 In your example, I wonder if you should unwrap before returning the value? If you did that then you'd already be unwrapping so this question would be somewhat less important. Do you think your function here should unwrap before returning, in terms of the guarantee/the contract it's trying to present to the caller

**Comment by skurfuerst** [comment]
Hey,

Actually my first intuition was to work without unwrap(), and in case an error occurred I would get the err return value in Golang filled.

Not sure if this answers your question :) 

All the best,
Sebastian

**Comment by myzie** [comment]
Hi @skurfuerst. As Risor (previously Tamarin) has evolved in the past few months, especially when the virtual machine was introduced, it became clear that it'd be better to adopt a more Python-esque error/exception pattern. I ended up removing the `Result` types and instead builtins raise errors as appropriate now.

I think this is overall more usable and less confusing than before, especially for scripting use cases. 

If you get a chance, give the new Risor a try and let me know what you think.
