### ISSUE TITLE
Recursively allow accessing structs

### ISSUE THREAD

**Issue by skurfuerst** [risor-io/risor#20]
Hey,

I am right now trying to access a nested struct; but this does not seem to work because the proxies are not built recursively.

Is this correct, and would this be changeable? :-) I think that would be very useful.

All the best,
and keep up the good work,
Sebastian

**Comment by myzie** [comment]
Yup I think you're right that this is a limitation right now - it can only proxy attributes at the top level of a struct. This did cross my mind as I worked on it, but I tabled it for the time being just due to time/effort.

How important is this to your project?

**Comment by skurfuerst** [comment]
Hey,

Not a big deal, I found a workaround for now :) 

All the best,
Sebastian

**Comment by myzie** [comment]
@skurfuerst this is now possible. I'm in progress on updating related docs, so standby for that.

**Comment by myzie** [comment]
Here's an example @skurfuerst -

https://github.com/risor-io/risor/blob/main/examples/go/struct/main.go#L86

Accessing nested structs is possible using map indexing syntax, e.g. `svc.GetState()["Counts"]["Start"]`
