### ISSUE TITLE
how does this compare with scriggo?

### ISSUE THREAD

**Issue by sprappcom** [risor-io/risor#244]
any benchmarks + alloc / ops to compare?

**Comment by dsikes** [comment]
fwiw - scriggo looks abandoned. At least this project is still being maintained.

**Comment by myzie** [comment]
`make bench` runs a Go benchmark on fibonacci(35) now fyi.

At the moment I don't have much time to run comparison benchmarks, but generally speaking Risor remains close to the fastest embedding scripting language for Go.
