### ISSUE TITLE
Odd behaviour unmarshalling json string containing `items` object

### ISSUE THREAD

**Issue by voigt** [risor-io/risor#247]
Hey,

lately I noticed an inconsistent while unmarshalling a json struct:

### What I did

* unmarshalling a json string containing an `items` object
* accessing the items object

```
issuesJson := `{
  "data": {
    "test": {
        "edges": [
        {"hello":"world"},
        {"hello":"world2"}
        ]
    },
    "items": {
        "edges": [
        {"hello":"world"},
        {"hello":"world2"}
        ]
    }
  }
}
`

issues := json.unmarshal(issuesJson)
print(issues.data.test)
print(issues.data.items)
```

### Which produced following output

```bash
$ risor main.rsr
map[edges:[map[hello:world] map[hello:world2]]]
0x102bc6380
```

### Expected output

```bash
$ risor main.rsr
map[edges:[map[hello:world] map[hello:world2]]]
map[edges:[map[hello:world] map[hello:world2]]]
```

### risor version

```bash
$ risor version 
1.6.0
```

I think this is a very odd behaviour, and probably not intended, as it prevents me from accessing any items of `data.items`.

**Comment by myzie** [comment]
Hi @voigt I will look at this.

**Comment by myzie** [comment]
Ah, yeah this is a bit confusing for sure. What is happening is that `items` is a built-in function on maps in Risor, like the `items` built-in on Python dicts.

Built-ins get priority over map attributes in an access like this.

The updated code to handle this case would use ["attr"] based access. This session in the REPL shows more:

```
Risor

>>> issues := {"items": [1,2,3]}
>>> issues
{"items": [1, 2, 3]}
>>> issues.items
builtin(map.items)
>>> issues.items()
[["items", [1, 2, 3]]]
>>> issues['items']
[1, 2, 3]
>>> 
```

I was a bit worried when I added map item access using `.attr` because of the potential for this confusion.

**Comment by myzie** [comment]
Improving the to-string formatting to show something more useful in the case you reported initially would be one way to make this a bit better.

**Comment by myzie** [comment]
@voigt I opened a PR that makes a few printing improvements. Want to give it a try? Wdyt?

**Comment by myzie** [comment]
The output of your script above becomes this now:

```
{"edges": [{"hello": "world"}, {"hello": "world2"}]}
builtin(map.items)
```
