### ISSUE TITLE
Set script's stdin/stdout/stderr file

### ISSUE THREAD

**Issue by dnbsd** [risor-io/risor#249]
When running risor as an embedded interpreter, output produced by user script is written to the default files `os.Stdout`, `os.Stderr`. Instead, I would like the output to be forwarded back to the user, which requires the ability to catch the output in an intermediary file or buffer. Similarly, although I do not have the use-case in mind, overriding the default Stdin could be desirable for some as well.

From the API standpoint this could be implemented as another `Option`:

```go
func WithStdout(*os.File) Option
func WithStderr(*os.File) Option
func WithStdin(*os.File) Option
```

The details elude me, but if someone can guide me to relevant parts of the code, I am willing to take on the challenge.

**Comment by myzie** [comment]
Hi @dnbsd, I think what you're looking for is possible today. I added a specific example just now:

https://github.com/risor-io/risor/blob/main/examples/go/isolated_io/main.go

Let me know what you think!

**Comment by dnbsd** [comment]
This indeed looks like something I can work with. Thank you very much! Great that you included it as an example too.
