### ISSUE TITLE
feature request: provide a default module path

### ISSUE THREAD

**Issue by rubiojr** [risor-io/risor#269]
It'd be nice if I could drop `.risor` modules in `~/.local/share/risor/modules` (OS dependent) and the interpreter would include that directory in the `--modules` path automatically.

**Comment by rubiojr** [comment]
As an alternative, and maybe a bit more flexible, being able to alter the module path at runtime from Risor scripts, like Python and Ruby do.

**Comment by myzie** [comment]
@rubiojr is this request relating to the Risor CLI specifically, or when using Risor as a library? I'm guessing you're using the CLI as-is but I want to make sure that's the case.

**Comment by rubiojr** [comment]
@myzie indeed, this would be useful when using the official CLI.

**Comment by rubiojr** [comment]
@myzie please ignore 🙏 . I didn't realize that because the CLI uses `github.com/spf13/viper` we can already `export RISOR_MODULES=<path>`. That works like a charm!

**Comment by myzie** [comment]
Aha! #winning
