### ISSUE TITLE
Find files in the file system that is cross platform 

### ISSUE THREAD

**Issue by gedw99** [risor-io/risor#275]
this repo is really useful .

I have a new to search for files based on file name , ext and file , and then with that result set pipe into some other command like rm -rf 

Any ideas ??

**Comment by myzie** [comment]
Hey there @gedw99 👋 

I'm not sure this is as concise as you'd like, but here's one way to do it:

```

func walk(path, suffix) {
    results := []
    filepath.walk_dir(".", func(path, dir_entry, err) {
        if path.has_suffix(".go") {
            results.append(path)
        }
    })
    return results
}

walk(".", ".go").each(func(path) { print(exec("ls", ["-l", path]).stdout) })
```

The `.each` call is needed to iterate over the paths list. Theoretically a future version of Risor could iterate over the list using a pipe expression or something like that, but it doesn't do it right now. This is a bit like how `xargs` is needed in some situations in bash.

Thoughts?

**Comment by myzie** [comment]
Open to suggestions on this front, but `filepath.walk_dir` is available and working.
