### ISSUE TITLE
Issue trying to add a PKI module

### ISSUE THREAD

**Issue by RachidMoysePolania** [risor-io/risor#287]
Hi, im trying to add a public key infrastructure module but when i push my branch i got this error:

_ERROR: Permission to risor-io/risor.git denied to RachidMoysePolania.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists._

how should i add the branch to be able to create the pull-request?
Thanks in advanced.

**Comment by rubiojr** [comment]
@RachidMoysePolania you may need to fork first, have a look at https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request and let me know if that helps

**Comment by myzie** [comment]
@RachidMoysePolania let us know how it's going with the PKI module. I'm closing this since this since it's not a Risor specific issue.
