### ISSUE TITLE
Index out of range when returning a named function

### ISSUE THREAD

**Issue by rubiojr** [risor-io/risor#288]
Should this be a valid construct?

```Go
func foo() {
  return func innerfunc() {
    print("foo")
  }
}

foo()
```

```
❯ risor test.risor
panic: runtime error: index out of range [-1]
```

The code works if an anonymous function is returned:

```Go
func foo() {
  return func() {
    print("foo")
  }
}

foo()
```

```
❯ risor test.risor
func() { ... }
```

**Comment by myzie** [comment]
Nice find. At a glance, that shouldn't be a valid construct because a named function declaration is a statement, not an expression. Only an expression should be allowed after a `return`.

Probably just need an additional check for this case... will look.

**Comment by myzie** [comment]
Thanks @rubiojr. I think this is fixed on `main` now. Let me know if you can confirm.

It ended up being more natural to let named functions be expressions, so they are now returnable as values.
