### ISSUE TITLE
REPL panic when calling functions from native Risor modules

### ISSUE THREAD

**Issue by rubiojr** [risor-io/risor#291]
To reproduce:

```
❯ cd tmp/

~/tmp
✦ ❯ mkdir lib

~/tmp
❯ echo 'func foo(){}' > lib/test.risor

~/tmp
❯ risor --modules lib
Risor

>>> import test
>>> test.foo
func foo() {  }
>>> test.foo()
panic: runtime error: invalid memory address or nil pointer dereference
>>>
```

Bisecting the commits it seems this broke somewhere between v1.3.2 and v1.4.0.

**Comment by rubiojr** [comment]
Looks like https://github.com/risor-io/risor/pull/186 could be the PR that caused the regression.

**Comment by rubiojr** [comment]
It seems `vm.loadedCode[rootCompiled]` returns `nil` in https://github.com/risor-io/risor/blob/5b8156697088bfb0950bf918dd9d70aa9c114a23/vm/vm.go#L881, but that's as far as I could get today.

**Comment by myzie** [comment]
Thanks @rubiojr. I think this is fixed on `main` now. Let me know if you can confirm.
