### ISSUE TITLE
Website is not readable

### ISSUE THREAD

**Issue by vjanelle** [risor-io/risor#55]
![image](https://github.com/risor-io/risor/assets/733641/6e601619-39d3-4631-8744-3f1287533944)

There may be some issues with your CSS on your website, it is barely readable.

**Comment by myzie** [comment]
Hi @vjanelle thanks for reporting this. The site really isn't ready for prime-time yet but I didn't realize how bad it looked on Chrome.

I just adjusted the CSS. Can you let me know if it's better for you?

**Comment by vjanelle** [comment]
Yes, that's a lot more readable.

**Comment by myzie** [comment]
Ok great, thank you. Yeah, exactly - the Golang Weekly mention was a nice surprise 😆
