### ISSUE TITLE
FR: os.getenv alias

### ISSUE THREAD

**Issue by randych-gilad** [risor-io/risor#64]
It's not a big deal but I think would fit into product's paradigm just fine.

**Comment by myzie** [comment]
@randych-gilad - what do you think, have the alias just be `getenv`, without needing the module prefix?

**Comment by randych-gilad** [comment]
@myzie I think this would be great if you also add its counterpart as alias in the same fashion.

**Comment by myzie** [comment]
Hi @randych-gilad, the v0.9.0 release includes `getenv`, `setenv`, and `unsetenv` aliases.

https://github.com/risor-io/risor/releases/tag/v0.9.0

You can get the update via brew upgrade risor or go install -tags aws github.com/risor-io/risor/cmd/risor@v0.9.0.
