### ISSUE TITLE
No aws support?

### ISSUE THREAD

**Issue by k-dahl** [risor-io/risor#66]
```
>>> client := aws.client("s3")
undefined variable: aws
```

I installed via `go install github.com/risor-io/risor/cmd/risor@v0.8.0`

**Comment by myzie** [comment]
Ah, @k-dahl thanks for asking about this.

Try this and let me know if it works - you have to supply the `aws` build tag right now:

```
go install -tags aws github.com/risor-io/risor/cmd/risor@v0.8.0
```

**Comment by k-dahl** [comment]
Thanks @myzie that did the trick!

Any chance of supporting Secrets Manager? 

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.20.1

**Comment by myzie** [comment]
Oh, wow, how did I miss secrets manager?? It definitely should be added.

I should be able to get to it in the next day or so, standby.

**Comment by myzie** [comment]
Hi @k-dahl, the v0.9.0 release includes AWS secretsmanager, as well as some others.

https://github.com/risor-io/risor/releases/tag/v0.9.0

You can get the update via `brew upgrade risor` or `go install -tags aws github.com/risor-io/risor/cmd/risor@v0.9.0`.

Let me know how it goes!
