### ISSUE TITLE
CallFunc isn't concurrent-safe

### ISSUE THREAD

**Issue by jakegut** [risor-io/risor#84]
I have multiple risor functions that I would like to execute a number of concurrently. I use the `CallFunc` that's with the context to achieve this. When I do this, I get inconsistent error messages. When I execute them sequentially I don't run into any errors.

A workaround might be to create multiple VMs (on-demand? or pool?), with the understanding that the risor function will not be able to have any side-effects.

**Comment by myzie** [comment]
Yeah, one VM is designed to be used from one goroutine only.

The [so far undocumented] intent is that you create new VMs on-demand. They're lightweight, so I'm not sure a pool is even really needed unless you were trying to do thousands of concurrent executions.

So given all that you should just call `result, err := risor.Eval(ctx, code, opts...)` in each concurrent execution.

If there's a particular consequence of that that's problematic definitely let me know. Thoughts?

**Comment by jakegut** [comment]
For my particular use case, I'm not too confident calling `Eval` for each concurrent execution. I have multiple builtins that cause side-effects in Go structs. What I'll probably do is deconstruct `Eval` in a way that generates the Code, evaluates it once, and then generate VMs based on that generated Code for concurrent executions. I'm glad to hear it's lightweight, I shouldn't even have more than 15 concurrent executions.

**Comment by myzie** [comment]
Opting out of using `Eval` like you mentioned is fine 👍 

Just curious - in your situation, would it be possible to use a mutex or channels in your builtins to achieve thread safety on that side? It sounds like the Go structs you mention need to be protected. If thread safety on that side was in place then perhaps multiple concurrent `Eval` calls would be fine?

**Comment by jakegut** [comment]
> It sounds like the Go structs you mention need to be protected

I went ahead with the on-demand VM solution and I ended up having to protect that Go struct since the VM has to be evaluated each time. I like this route as I only need to parse and compile once and not for each execution. I do question the context that's being created and passed around (if it's for the original VM that evaluated or for the new one). I think if the `vm.codeFunc` was exported I wouldn't worry have to worry about this issue. However, the solution has been working for me.

**Comment by jakegut** [comment]
> However, the solution has been working for me.

It's not working... just less flaky than before.

**Comment by myzie** [comment]
@jakegut - if you're able to share some representative code that demonstrates the problem, I'd definitely take a look.

FWIW, on a Risor branch that's close to ready I improved the APIs around reusing a compiled Code struct that could be relevant for your situation. I'll keep you updated on that.

**Comment by jakegut** [comment]
[This is an example](https://github.com/jakegut/risor/blob/86fee810f33968870a018c68c71ca11aa8945742/examples/go/conc/main.go) of what I was trying to do for concurrent execution. It runs sometimes, errors out most of the time. My guess is that the context has a `CodeFunc` that's from the original evaluation of the VM in the `main` function, and that's why this doesn't work.

In a branch of my fork, [I made the CodeFunc exported](https://github.com/risor-io/risor/compare/main...jakegut:risor:jake/vm) as a workaround.

**Comment by myzie** [comment]
@jakegut you might want to play around with the new `Call` function on this branch:

https://github.com/risor-io/risor/blob/code-objects/risor.go#L88-L107
https://github.com/risor-io/risor/blob/code-objects/risor_test.go#L154-L170

This should mean you don't need to change CodeFunc in that way.

This is still only safe for use from 1 goroutine, but it would be easy to wrap this new `Call` function with a mutex to serialize calls from multiple goroutines if you want.

**Comment by jakegut** [comment]
> the new `Call` function

I'll need to be calling anonymous functions, which I already have an `*object.Function` of, so I'm not sure if this `Call` applies to my use case and I'll need to fall back on `CodeFunc`.

**Comment by myzie** [comment]
@jakegut - I riffed on your example and came up with this:
https://github.com/risor-io/risor/compare/conc?expand=1

It has some commonality with what you were trying to do:
- Concurrent Risor executions
- Concurrent calls against a service
- Providing `runFunc` to the Risor script

But it's different in that it doesn't reuse the CallFunc in the same way. Is this close to achieving what you're trying to do?

**Comment by jakegut** [comment]
> Is this close to achieving what you're trying to do?

Unfortunately, I don't think so. That `taskKV` was pretty important in my use-case and there will be multiple `runFunc`s so executing all of them at once isn't really an option. At this point, I think it's important to disclose what I'm trying to do (not that it was "top-secret" before, just didn't think it was necessary). I'm making a build system where risor is the "configuration" language for it. So there will be multiple targets, each with its' own set of dependencies and a function to execute the target. I'd like there to be some level of concurrency (not too much, just able to run 3-5 targets concurrently). If you're curious [here's the repo](https://github.com/jakegut/yabs) with most of the risor action happening in [this file](https://github.com/jakegut/yabs/blob/main/cmd/yabs/eval.go). However, I don't want you to feel obligated and sink some time in this repo. I just hope that you appreciate the transparency.

**Comment by myzie** [comment]
Ah, nice! I'll think about this more and browse your project.

FWIW, I was the primary author of a caching build system written in Go:

https://github.com/fugue/zim

I'm not actively working on that these days. Feel free to borrow ideas or anything else relevant from that!

**Comment by myzie** [comment]
@jakegut - do you have any thoughts on what built-in Risor support for calling functions concurrently might look like?

Maybe we could do something akin to the `conc` library's API:
https://github.com/sourcegraph/conc#examples

We'll need to cleanly pass inputs and outputs to/from the workers and perhaps the workers may execute in their own Risor VMs (as an implementation detail).

**Comment by jakegut** [comment]
> what built-in Risor support for calling functions concurrently might look like

Concurrently or concurrent-safe? Personally, I think I'd prefer concurrent-safe so I have some level of control when calling functions and allow the implementer use whatever means of calling them concurrently. In my case, I'm already calling a Go function concurrently, when then runs the user-defined Risor function. The multi-level concurrency might make it harder to debug.

For executing Risor functions concurrently, maybe something more similar to `conc`'s [`Pool`](https://pkg.go.dev/github.com/sourcegraph/conc/pool#example-Pool):

```go
p := risor.NewFnPool()
outputs := make(chan object.Object, 5)
for i := 0; i < len(outputs); i++ {
       ch, err := p.Fn(ctx, <risor Fn object or name>, <args: []object.Object>) // returns `(chan object.Object, error)
       // handle error
       outputs[i] = ch // or another way to mutate array safely
}
p.Wait() 

// loop over outputs
for _, ch := outputs {
       obj := <-ch
      // handle object.Object
}
```
This is similar to yabs's scheduler. But that could be a more "low-level" API and have another, higher-level, alternative:

```go
args := [][]object.Object{...} // 2D slice representing the args for each fn invocation
objs, err := risor.ForEachFn(ctx, <risor Fn object or name>, args) // returns ([]object.Object, error)
// handle error
// handle objs
```

**Comment by myzie** [comment]
@jakegut - did the `vm.Clone()` function help resolve the situation for your use case?

**Comment by jakegut** [comment]
The `vm.Clone()` has worked out really well and I haven't run into any issues. I'll let you know if I run into any.

**Comment by myzie** [comment]
Ok great. I'll close this since an alternative approach is available 👍
